name: flutter_clean_melos_workspace

packages:
  - apps/flutter_app
  - packages/api_client
  - packages/core
  - packages/core_ui
  - packages/database

command:
  bootstrap:
    usePubspecOverrides: true
    hooks:
      post: dart pub get

scripts:
  analyze:
    run: melos exec -- "dart analyze ."
    description: Run analysis in all packages.

  test:
    run: melos exec --dir-exists=test -- "flutter test"
    description: Run tests in all packages.

  build:runner:
    run: melos exec --depends-on=build_runner -- "dart run build_runner build --delete-conflicting-outputs"
    description: Run build_runner in all packages that depend on it.

  # Script compuesto para configuración inicial (Funciona en Windows/Mac/Linux)
  # Melos maneja el chaining de comandos (&&) internamente de forma cross-platform.
  setup:
    run: |
      melos bootstrap && \
      melos run build:runner && \
      melos run validate
    description: Configura todo el entorno: Bootstrap -> Build Runner -> Validate.

  validate:
    run: |
      melos run analyze && \
      melos run test
    description: Run full validation suite (Analyzer + Tests). Agent MUST run this before finishing a task.
